### ISSUE TITLE
Upgrade ALICA against the new Micro-Manager 2.0 Gamma API

### ISSUE THREAD

**Issue by kmdouglass** [LEB-EPFL/ALICA#17]
The new revision of Micro-Manager 2.0 (called Micro-Manager 2.0 Gamma) both upgrades the Java version used by MM to 1.8 and introduces some slight API changes.

ALICA should be compiled against this new version to ensure it keeps working with the most up-to-date MM.

http://micro-manager.3463995.n2.nabble.com/Sorry-to-ask-here-but-is-Open-Imaging-in-business-I-can-t-seem-to-get-a-response-from-them-tt7588904.html#a7589069

**Comment by MStefko** [comment]
I can take care of this together with the Maven build. Do you think we can abandon JDK_1.6 in favor of JDK_1.8 for further versions of ALICA altogether?

**Comment by kmdouglass** [comment]
Great! Thanks Marcel!

Yes I think we can switch to JDK 1.8 permanently. I will see Mark in Goettingen and will ask him in person to confirm that they are moving over to 1.8.

**Comment by kmdouglass** [comment]
See http://micro-manager.3463995.n2.nabble.com/A-few-questions-about-Micro-Manager-2-0gamma-tc7589403.html for more information.

**Comment by kmdouglass** [comment]
I'm making a note of the changes to the API that will cause conflicts here. There are still changes being made to 2.0gamma, so this list is neither final, nor are the items in the list fixed.

1. Class: **Analysis Worker**: `NewImageEvent` has been replaced by `org.micromanager.data.DataProviderHasNewImageEvent`
2. Class: **Analysis Worker**: `DataViewer.getDatastore()` has been deprecated.

**Comment by kmdouglass** [comment]
ALICA is now working in Java 1.8 and on Micro-Manager 2.0gamma. Mark says he aims 2.0 gamma into the main MM 2.0 branch some time mid-summer, so once this happens ALICA will be MM2.0 compatible in general.

See #21
